services:
  server:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
      - ./uploads:/app/uploads
      - ./thermal:/app/thermal
      - ./calibration:/app/calibration
      - ./processed:/app/processed
      - ./annotated:/app/annotated
      - ./failed:/app/failed
      - ./dataset:/app/dataset
      - ./upload_log.txt:/app/upload_log.txt
      - ./processed_log.txt:/app/processed_log.txt
      - ./annotation_log.txt:/app/annotation_log.txt
    restart: unless-stopped
